function qdemos
% QDEMOS For setting up qo toolbox demos

%   Sze Tan 1999

labelList=str2mat( ...
        'Atom in cavity (steady-state)', ...
        'Steady-state (improved)', ...
   	  'Orbital angular momentum', ...
        'Direction eigenket', ...
        'Clebsch-Gordon via diagonalization',...
        'The GHZ state',...
   	  'Schrodinger cat state', ...
        'Squeezed state', ...
        'Rotating world', ...
        'Partial traces', ...
        'Atom+cavity via eseries (time-evolution)', ...
        'Correlations and spectra', ...
        'Light force on stationary atom', ...
        'Force on moving 2-level atom', ...
        'Force on moving multi-level atom 1', ...
        'Force on moving multi-level atom 2', ...
        '*Atom+cavity via odesolve',...
        '*Force on moving atom via odesolve',...
        '*Lossy 2-sided cavity, Q Monte Carlo',...
        '*Atom+cavity via Q Monte Carlo',...
        '*Force on moving atom, Q Monte Carlo',...
        '*Lossy 2-sided cavity, state diffusion',...
        '*Atom+cavity via state diffusion',...
        '*State transfer, Schrodinger eqn',...
        '*State transfer, master eqn',...
        '*State transfer, Q Monte Carlo',...
        '*State transfer, state diffusion'...
     );
nameList=str2mat( ...
	'xprobss', ...
	'xprobss2', ...
   'xorbital',...
   'xdirection',...
   'xclebsch',...
   'xghz',...
   'xschcat',...
   'xsqueeze',...
   'xrotateworld',...
   'xptrace',...
   'xprobevolve', ...
   'xprobcorr', ...
   'xprobstatic', ...
   'xprob2lev', ...
   'xprobmulti1', ...
   'xprobmulti2', ...
   'xprobintmaster', ...
   'xprobtimedep', ...
   'xprobqmc1', ...
   'xprobqmc2', ...
   'xprobtimedep1', ...
   'xprobdiffuse1', ...
   'xprobdiffuse2', ...
   'xadiab1',...
   'xadiab2',...
   'xadiab3',...
   'xadiab4'...
   );
demowin(labelList,nameList);
